services:
  - type: web
    name: sales-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python -m src.train --input-path data/processed/processed.csv
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: HOST
        value: 0.0.0.0

  - type: web
    name: sales-frontend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BACKEND_URL
        sync: false
